# Generated by Django 3.2.3 on 2021-07-18 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, max_length=200, upload_to='images'),
            preserve_default=False,
        ),
    ]
